# Generated by Django 2.0.6 on 2018-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180626_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contenu',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='pseudo',
            field=models.CharField(default='', max_length=42),
            preserve_default=False,
        ),
    ]
