# Generated by Django 2.0.6 on 2018-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180626_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Le commentaire est visible ?'),
        ),
    ]
