# Generated by Django 2.0.6 on 2018-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contenu',
            field=models.TextField(),
        ),
    ]
