# Generated by Django 2.0.6 on 2018-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180627_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contenu',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
